PreguntMatic/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'PreguntMatic.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', 'eines.views.home', name='home'),
    url(r'^avisLegal$', 'eines.views.politicaIAvis', name='politicaIAvis'),
    url(r'^preguntes/', include('Preguntes.urls', namespace='preguntes')),
    url(r'^usuaris/', include('Usuaris.urls', namespace='usuaris')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^erroret500$','eines.views.error500',name='erroret500'),
)

Preguntes/urls.py
from django.conf.urls import patterns, url
from Preguntes import views 

urlpatterns = patterns('',
    url(r'^crearPregunta$', views.crearPregunta, name='crearPregunta'),
    url(r'^crearTema$', views.crearTema, name='crearTema'),
    url(r'^llistatTipus$',views.llistatTipus,name='llistatTipus'),
    url(r'^preguntesTipus/(?P<tipusPregunta>\w+)$', views.practicarTipus, name='practicarTipus'),
    url(r'^afegirResposta', views.afegirResposta, name='afegirResposta'),
    url(r'^$',views.ferPreguntes,name='ferPreguntes'),
    url(r'^estadistiques$',views.estadistiques,name='estadistiques'),
    url(r'^preguntesIncorrectes$',views.preguntesIncorrectes,name='preguntesIncorrectes'),
    url(r'^exportXML$',views.exportXML,name='exportXML'),
    url(r'^randomExamen$',views.randomExamen,name='randomExamen'),
    url(r'^eliminarNotificacio$',views.eliminarNotificacio,name='eliminarNotificacio'),
    url(r'^llistatPreguntesIncorrectes$',views.llistatPreguntesIncorrectes,name='llistatPreguntesIncorrectes'),
)

Usuaris/urls.py
from django.conf.urls import patterns, url
from Usuaris import views 

urlpatterns = patterns('',
    url(r'^login$', views.entrada, name='login'),
    url(r'^logout$', views.logout_view, name='logout'),
    url(r'^registre$',views.registrar,name='registre'),
    url(r'^perfil$',views.perfil,name='perfil'),
    url(r'^afegirPuntsUsuari$',views.afegirPuntsUsuari,name='afegirPuntsUsuari'),
    
)

Preguntes/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import safe
from django.conf.urls import patterns
from django.db.models import Avg
import re
# Create your models here.

class tema(models.Model):
    nom = models.CharField(max_length=100,unique= True)
    
    def __unicode__(self):
        return self.nom
    
class tipus(models.Model):
    nom = models.CharField(max_length=100,unique= True)
    
    def __unicode__(self):
        return self.nom

class pregunta(models.Model):
    tema = models.ForeignKey(tema)
    usuari = models.ForeignKey(User)
    tipus = models.ForeignKey(tipus)
    enunciat =  models.TextField(max_length=500)

    def __unicode__(self):
        return self.enunciat
    
    def mitjana(self):
        m = self.puntuacio_set.aggregate(mitjana = Avg('notaUsuari'))
        return m['mitjana']
    
    #Generar array de respostes
    def getRespostes(self):
        enunciat = self.enunciat
        respostes = re.findall(r"\[([A-Za-z]+)\]",enunciat)
        return respostes
        
    #Transformar l'enunciat a HTML
    def toHTML(self):
        text = self.enunciat
        canvi = ""
        if self.tipus.nom == "CompletarGramatica":
            canvi = "<input class='resposta form-control' type='text'><br>"
        if self.tipus.nom == "EmplenarBuitsOrtografics":
            canvi = "<input class='form-control  inputPetit resposta' type='text'>"
        return safe(re.sub(r'\[\w+\]',canvi, text))
    
    
    
class puntuacio(models.Model):
    pregunta = models.ForeignKey(pregunta)
    usuari = models.ForeignKey(User)
    notaUsuari = models.IntegerField()
    data = models.DateField(auto_now_add=True,editable=False)
    hora = models.TimeField(auto_now_add=True,editable=False)
    correctes = models.IntegerField()
    incorrectes = models.IntegerField()
    
    def __unicode__(self):
        return self.notaUsuari
    
class preguntaErronea(models.Model):
    pregunta = models.ForeignKey(pregunta)
    usuariNotifica = models.ForeignKey(User)
    data = models.DateField(auto_now_add=True,editable=False)
    hora = models.TimeField(auto_now_add=True,editable=False)
    
    

Preguntes/forms.py
from django import  forms
from Preguntes.models import pregunta, tema,puntuacio ,preguntaErronea

class formulariPregunta(forms.ModelForm):
    class Meta:
        model = pregunta
        fields = ['tema','tipus','enunciat']
        
class formulariTema(forms.ModelForm):
    class Meta:
        model = tema
        fields = ['nom']
        
class formulariPreguntaErronea(forms.ModelForm):
    class Meta:
        model = preguntaErronea
        exclude = ['data','hora','usuariNotifica',]
        
class formulariResposta(forms.Form):
    idPregunta = forms.IntegerField()
    respostes = forms.CharField(max_length=300)
    
class formulariEliminarNotifiacio(forms.Form):
    idPregunta = forms.IntegerField()
    

    

    

Preguntes/views.py
# -*- encoding: utf-8 -*-
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from Preguntes.forms import formulariPregunta, formulariTema, formulariResposta, formulariPreguntaErronea, formulariEliminarNotifiacio
from django.contrib import messages
from django.http.response import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from Preguntes.models import tema, pregunta, tipus,puntuacio,preguntaErronea
from django.contrib.auth.models import User
from django.core import serializers
from django.http import HttpResponse
from Usuaris.models import usuari, medallesUsuari
from django.db.models import Count
import json, random
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

#Elimina les entrades a la BDD de la pregunta, perquè no es erronia
@login_required
def eliminarNotificacio(request):
    medalles = medallesUsuari.objects.filter(usuari = request.user)
    pot = False
    for m in medalles:
        if m.medalla.nomMedalla == 'EliminarPreguntes':
            pot = True
    if pot:
        if request.method == 'POST':
            form = formulariEliminarNotifiacio(request.POST)
            if form.is_valid():
                idP=form.cleaned_data['idPregunta']
                pregun = pregunta.objects.filter(pk = idP)
                notif = preguntaErronea.objects.filter(pregunta = pregun)
                for n in notif:
                    n.delete()
                messages.success(request,'Notificació enviada')
                msg = "ok"
            else:
                msg = "fail"
                messages.error(request, 'Hi ha hagut un error al notificar')
            return HttpResponse(msg)
    else:
        messages.error(request,'No tens permís per veure això!')
        return HttpResponseRedirect(reverse('home'))

#Exporta les preguntes en XML
@login_required
def exportXML(request):
    data = serializers.serialize("xml", pregunta.objects.all())
    return HttpResponse(data, content_type="application/xml")

#-----------No es fa servir?
@login_required
def modificarPreguntes(request):
    medalles = medallesUsuari.objects.filter(usuari = request.user)
    pot = False
    for m in medalles:
        if m.medalla.nomMedalla == 'EliminarPreguntes':
            pot = True
    if pot:
        if request.method == 'POST':
            form = formulariResposta(request.POST)
            if form.is_valid():
                idP=form.cleaned_data['id']
                enunP = form.cleaned_data['enunciat']
                form.save()
                messages.success(request,'Notificació enviada')
                msg = "ok"
            else:
                msg = "fail"
                messages.error(request, 'Hi ha hagut un error al notificar')
            return HttpResponse(msg)
    else:
        messages.error(request,'No tens permís per veure això!')
        return HttpResponseRedirect(reverse('home'))

#Mostra les preguntes marcades com erroneas. Per modificar la pregunta anira a un altre vista
@login_required
def llistatPreguntesIncorrectes(request):
    preguntesIn = []
    medalles = medallesUsuari.objects.filter(usuari = request.user)
    pot = False
    for m in medalles:
        if m.medalla.nomMedalla == 'EliminarPreguntes':
            pot = True
    if pot:
        
        incor = preguntaErronea.objects.values('pregunta').annotate(recompte = Count('pregunta'))
        for i in incor:
            if i['recompte'] > 5:
                p =  get_object_or_404(pregunta, pk=i['pregunta'])
                preguntesIn.append(p)
        
        return render(request,'llistatPreguntesIncorrectes.html',{'preguntesIn':preguntesIn,})
    else:
        messages.error(request,'No tens permís per veure això!')
        return HttpResponseRedirect(reverse('home'))
        
                    
        
#Nomes poden entrar els de la medalla ReportarPregunta
#Marca la pregunta com a incorrecte
@login_required
def preguntesIncorrectes(request):
    medalles = medallesUsuari.objects.filter(usuari = request.user)
    pot = False
    for m in medalles:
        if m.medalla.nomMedalla == 'ReportarPregunta':
            pot = True
    
    if pot:
        if request.method == 'POST':
            preg = preguntaErronea()
            preg.usuariNotifica = request.user
            form = formulariPreguntaErronea(request.POST,instance = preg)
            if form.is_valid():
                form.save()
                messages.success(request,'Notificació enviada')
                #return HttpResponseRedirect(reverse('home'))
                msg = "ok"
            else:
                msg = "fail"
                messages.error(request, 'Hi ha hagut un error al notificar')
            return HttpResponse(msg)
    else:
        messages.error(request,'No tens permís per veure això!')
        return HttpResponseRedirect(reverse('home'))
        
#Nomes poden entrar els de la medalla CrearPreguntes
@login_required
def crearPregunta(request):
    medalles = medallesUsuari.objects.filter(usuari = request.user)
    pot = False
    for m in medalles:
        if m.medalla.nomMedalla == 'CrearPreguntes':
            pot = True
    if pot:
        preg = pregunta()
        preg.usuari = request.user
        if request.method == 'POST':
            form = formulariPregunta(request.POST,instance = preg)
            if form.is_valid():
                form.save()
                messages.success(request,'Pregunta introduida correctament')
                return HttpResponseRedirect(reverse('home'))
            else:
                messages.error(request, 'Hi ha hagut un error al introduir la pregunta')
        else:
            form = formulariPregunta(instance = preg)
            
        camps_bootestrapejar =( 'tema', 'tipus','enunciat')
        for c in camps_bootestrapejar:
            form.fields[c].widget.attrs['class'] = 'form-control'
        return render(request, 'crearPregunta.html', {'form':form,})
    else:
        messages.error(request,'No tens permís per veure això!')
        return HttpResponseRedirect(reverse('home'))
    
#Per AJAX arriba un formulari amb el necessari per corregir
@login_required
def afegirResposta(request):
    if request.method == 'POST':
        form = formulariResposta(request.POST)
        if form.is_valid():
            idPregunta = form.cleaned_data['idPregunta']
            respostes = form.cleaned_data['respostes']
            pregun = get_object_or_404(pregunta,pk=idPregunta)
            nota = 0
            correcte = 0
            incorrecte = 0
            arrayRespostesUsuari = respostes.split(',')
            #El model té una funció que retorna les respostes en un array
            arrayRespostesCorrectes = pregun.getRespostes()
            #Comprovació de les respostes
            #La comprovació de les respostes canvia segons el tipus de la pregunta.
            if pregun.tipus.nom == "EmplenarBuitsOrtografics":
                for i in xrange(len(arrayRespostesCorrectes)):
                    if arrayRespostesCorrectes[i].lower() == arrayRespostesUsuari[i].lower():
                        correcte= correcte+1
                    else:
                        incorrecte = incorrecte+1
            else:
                for i in arrayRespostesUsuari:
                    if i.lower() in arrayRespostesCorrectes:
                        correcte = correcte +1
                    else:
                        incorrecte = incorrecte+1
            notaPerPregunta = 10/(correcte+incorrecte)
            nota = correcte*notaPerPregunta  
            puntu = puntuacio()
            puntu.pregunta = pregun
            puntu.usuari = request.user
            puntu.notaUsuari = nota
            puntu.correctes = correcte
            puntu.incorrectes = incorrecte
            puntu.save()
            #Sumar punts si ha aprovat!
            if nota >= 5:
                useret = usuari.objects.filter(user = request.user).get()
                useret.punts = useret.punts+2
                useret.save()
                messages.info(request,'Has guanyat dos punts al contestar la pregunta')
            #messages.success(request,'Dades enviadades correctament')
            #preparem la llista de noms a enviar
            resposteta =  {"idPregunta": idPregunta, 
                            "nota": nota,
                            "correctes":correcte,
                            "incorrectes":incorrecte
                            }
        return HttpResponse(json.dumps(resposteta), content_type="application/json")
            
    else:
        messages.error(request,'No tens permís per veure això!')
        return HttpResponseRedirect(reverse('home'))
    
#Nomes poden entrar els de la medalla crear preguntes -- Si poden crear preguntes podran crear temes
@login_required
def crearTema(request):
    pot = False
    medalles = medallesUsuari.objects.filter(usuari = request.user)
    for m in medalles:
        if m.medalla.nomMedalla == 'CrearPreguntes':
            pot = True
    
    if pot:
        if request.method == 'POST':
            form = formulariTema(request.POST)
            if form.is_valid():
                form.save()
                messages.success(request,'Tema introduit correctament')
                msg = "ok"
                t = tema.objects.filter(nom=form.cleaned_data['nom']).get()
                msg =  {"id": t.id, 
                            "nom": t.nom,
                            }
            else:
                msg = {"fail":"fail"}
                messages.error(request, 'Hi ha hagut un error al introduir el tema')
            return HttpResponse(json.dumps(msg), content_type="application/json")
    else:
        messages.error(request,'No tens permís per veure això!')
        return HttpResponseRedirect(reverse('home'))
    
#Mostra totes les preguntes
@login_required
def randomExamen(request):
    totesPreguntes = pregunta.objects.all()

Preguntes/templates/--puntuacio.html
{% extends "base.html" %}

{% block  title %}Crear tema{% endblock %}

{% block localitzacio %}
		<li>
			<a href="{% url 'preguntes:ferPreguntes' %}">Preguntes</a>
		</li>
		<li>
			<a class="active">Crear Tema</a>
		</li>
{% endblock %}


{% block content %}
<h1>Creació de temes</h1>
<form action="" method="post" enctype="multipart/form-data" class="form-horizontal" role="form">
	{% csrf_token %}
	{% for field in form.visible_fields %}
	<div id="formEntradaTemes" class="col-md-6  form-group">
		{{ field.errors }}
		{{ field.label_tag }} {{ field }}
	</div>
	{% endfor %}
	<div class="col-md-6 col-md-offset-3">
		<input class="btn btn-default" type="submit" value="Envia" />
	</div>
</form>

{% endblock %}

Preguntes/templates/crearPregunta.html
{% extends "base.html" %}

{% block  title %}Crear pregunta{% endblock %}

{% block localitzacio %}
<li>
	<a href="{% url 'preguntes:ferPreguntes' %}">Preguntes</a>
</li>
<li>
	<a class="active">Crear Pregunta</a>
</li>
{% endblock %}

{% block content %}
<div class="col-md-10 col-md-offset-0">
	<h1>Creació de preguntes</h1>
	<button class="col-md-5 col-md-offset-3 btn btn-info btn-md" data-toggle="modal" data-target="#nouTema">
		No trobes el tema que vols? Crea'l!
	</button>
	<form action="" method="post" enctype="multipart/form-data" class="form-horizontal" role="form">
		{% csrf_token %}
		<button class="btn btn-default"  data-toggle="modal" data-target="#exempleTipus" >Veure exemples</button>
		{% for field in form.visible_fields %}
		<div  class="col-md-12  form-group">
			{{ field.errors }}
			{{ field.label_tag }} {{ field }}
		</div>
		{% endfor %}
		<div class="col-md-6 col-md-offset-3">
			<input class="btn btn-primary btn-block" type="submit" value="Envia" />
		</div>
	</form>
</div>


<!-- Modal -->
<div class="modal fade" id="exempleTipus" tabindex="-1" role="dialog" aria-labelledby="exempleTipusLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div id="textModalTipus" class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>


<div class="modal fade" id="nouTema" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
					&times;
				</button>
				<h4 class="modal-title" id="myModalLabel">Afegir nou tema</h4>
			</div>
			<div class="modal-body  " >
				<input type="text" id="id_nom" class="form-control " placeholder="Nom del Tema"/>
				
			</div>
			<div class="modal-footer">
				
					<input class="btn btn-default" id="afegirTema" data-dismiss="modal" type="submit" value="Guardar" />
				
				<button type="button" class="btn btn-warning" data-dismiss="modal">
					Tancar
				</button>

			</div>
		</div>
	</div>
</div>

{% endblock %}

Preguntes/templates/estadistiques.html
{% extends "base.html" %}

{% block  title %}Estadistiques{% endblock %}

{% block localitzacio %}
<li>
	<a href="{% url 'preguntes:ferPreguntes' %}">Preguntes</a>
</li>
<li>
	<a class="active">Estadistiques</a>
</li>
{% endblock %}

{% block content %}


<h1 class="text-center">Estadistiques</h1>

<ul class=" nav-tabs nav-justified nav ">
  <li id="mevesNotes" class="butonets"><a  href="#">Evolució de les meves notes</a></li>
  <li id="mevesPreguntes" class="butonets"><a href="#">Mitjana nota meves preguntes</a></li>
</ul>

<div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"><p class="lead text-center">Escull el gràfic que vols veure </p></div>
{% endblock %}
{% block mesScripts %}
<script type="application/javascript">
$(document).ready(function() {
	
	 });
$('#mevesPreguntes').click(function (){
	$('.butonets').removeClass('active');
	$('#mevesPreguntes').addClass('active butonets');
	$('#container').empty();
	{% if mevesPreguntes %}
	$('#container').highcharts({
            chart: {
                type: 'column'
            },
            title: {
                text: 'Notes mitjanes de les meves preguntes'
            },
            subtitle: {
                text: ''
            },
            xAxis: {
            	title: {
                    text: 'Pregunta - Tema'
                						},
                type: 'category',
                labels: {
                    rotation: -45,
                    style: {
                        fontSize: '13px',
                        fontFamily: 'Verdana, sans-serif'
                    }
                }
            },
            yAxis: {
                min: 0,
                title: {
                    text: 'Nota'
                }
            },
            legend: {
                enabled: false
            },
            tooltip: {
                pointFormat: '',
            },
            series: [{
                name: 'Preguntes Creades per mi ',
                data: [
                	{% for c in mevesPreguntes %}
                	["{{c.id}}-{{c.tema}}",
						{{c.mitjana|stringformat:".3f"}}
						],
					{% endfor%}
                    
                ],
                dataLabels: {
                    enabled: true,
                    rotation: -90,
                    color: '#FFFFFF',
                    align: 'right',
                    x: 4,
                    y: 10,
                    style: {
                        fontSize: '13px',
                        fontFamily: 'Verdana, sans-serif',
                        textShadow: '0 0 3px black'
                    }
                }
            }]
        });
        {% else %}
        $('#container').empty().append("<h3>No hi ha dades perquè no has creat preguntes<br><a class='btn btn-default' href='{% url 'preguntes:crearPregunta' %}'>Crea-la ara mateix!</a>");
        {% endif %}
        
});

	/*
	 * Gràfic per pregunta
	 */
	$('#mevesNotes').click(function () {
		{% if punts %}
		$('.butonets').removeClass('active');
		$('#mevesNotes').addClass('active butonets');
		$('#container').empty;
        $('#container').highcharts({
            title: {
                text: 'Evolució de les meves notes',
                x: -20 //center
            },
            subtitle: {
                text: '',
                x: -20
            },
            xAxis: {
            	title: {
                    text: ''
                						},
                categories: [
               	 {% for d in punts %}
					'{{d.data|date:"d/m/y"}}',
				{% endfor %}
				],
				labels: {
                    rotation: -45,
                    style: {
                        fontSize: '13px',
                        fontFamily: 'Verdana, sans-serif'
                    }
                }
            },
            yAxis: {
                title: {
                    text: 'Notes'
                						},
                plotLines: [{
                    value: 0,
                    width: 1,
                    color: '#808080'
                }]
            },
            tooltip: {
                valueSuffix: ''
            },
            legend: {
                layout: 'vertical',
                align: 'right',
                verticalAlign: 'middle',
                borderWidth: 0
            },
            series: [{
                name: '{{request.user.username}}',
                data: [
                {% for p in punts %}
					{{ p.notaUsuari|floatformat }},
				{% endfor %}
                ]
            },
            ]
        });
        
        {% else %}
        
        $('#container').empty().append("<h3>No hi ha dades perquè no has respòs preguntes<br><a class='btn btn-default' href='{% url 'preguntes:ferPreguntes' %}'>Comença ara mateix!</a>");
        {% endif %}
    });
    
    
    
</script>

{% endblock %}

Preguntes/templates/llistatTipus.html
{% extends "base.html" %}
{% load staticfiles %}
{% block  title %}Llistat de tipus{% endblock %}
{% block localitzacio %}
		<li>
			<a href="{% url 'preguntes:ferPreguntes' %}">Preguntes</a>
		</li>
		<li>
			<a class="active">Llistat de Tipus</a>
		</li>
{% endblock %}
{% block content %} 
<h1>Tipus disponibles</h1>
<strong>Escull el tipus que vulguis pràcticar</strong><br><br>
{% if tipus %}
<div class="container">
	<ul>
			<div class="list-group col-md-8 col-sm-offset-2 ">
			{% for tip in tipus %}
				<div class="list-group-item text-center">
					<a href="{% url 'preguntes:practicarTipus' tip.id %}"><p>{{ tip.nom }} </p></a>
				</div>
			{% endfor %}
			</div>
	</ul>
</div>
{% else %}
<p>
	No hi ha cap pregunta disponible del tema
</p>
{% endif %} {% endblock %}

Preguntes/templates/preguntesTipus.html
{% extends "base.html" %}
{% load staticfiles %}

{% block  title %}Tema: {{ tema.nom }}{% endblock %}
{% block localitzacio %}
<li>
	<a href="{% url 'preguntes:ferPreguntes' %}">Preguntes</a>
</li>
<li>
	<a href="{% url 'preguntes:llistatTipus' %}">Llistat Tipus</a>
</li>
<li>
	<a class="active">Tipus: {{ tipus }}</a>
</li>
{% endblock %}

{% block content %}

<h1>Respon les preguntes del tipus {{tipus.nom}}</h1>
<br>
{% if preguntesTipus %}
<div class="container">

	<div  class="row">

		<ul>
			{% for pregunta in preguntesTipus %}

			<div id="taulaResultats{{pregunta.id}}" class=" taulaResultats  table-responsive">
				<table class=" table-bordered table  col-md-3 table-condensed">
					<tr class="info">
						<td>Nota mitjana de la pràctica: </td><td id="nota{{pregunta.id}}"></td>
					</tr>
					<tr  class="success">
						<td>Respostes Correctes: </td><td id="correctes{{pregunta.id}}"></td>
					</tr>
					<tr class="danger">
						<td>Respostes Incorrectes: </td><td id="incorrectes{{pregunta.id}}"></td>
					</tr>
				</table>
			</div>

			<div id="{{pregunta.id}}"  class="list-group col-md-9">
				<p class='list-group-item-info list-group-item'>
					<span class="col-md-4">Emplena els buits amb {{ pregunta.tema }}</span>
					<span class="btn-group col-md-offset-1">
						<button onclick="validarPreguntes({{pregunta.id}})" id="valid{{pregunta.id}}" class="btn col-md-offset-2 btn-sm btn-info butonet  validarPreguntes" value="Validar Pregunta" >
							Validar Pregunta
						</button> {%if medalles %}
						{%for m in medalles %}
						{% if 'ReportarPregunta' == m.medalla.nomMedalla %}
						<button onclick="marcarIncorrecte({{pregunta.id}})" id="repor{{pregunta.id}}"  class="btn butonet col-md-offset-1 btn-sm btn-warning" value="Reportar Pregunta Incorrecte ">
							Reportar Pregunta Incorrecte
						</button> 
						{%endif%}
						{%endfor%}
						{%endif%} <span class="twitter" id="twitter{{pregunta.id}}"><a href="https://twitter.com/intent/tweet?button_hashtag=PreguntMatic&text=He%20contestat%20una%20pregunta%20sobre%20{{pregunta.tema}}%20a%20" class=" twitter-hashtag-button" data-lang="es" data-related="juli16_31">Tweet #PreguntMatic</a>
							<script>
								! function(d, s, id) {
									var js, fjs = d.getElementsByTagName(s)[0], p = /^http:/.test(d.location) ? 'http' : 'https';
									if (!d.getElementById(id)) {
										js = d.createElement(s);
										js.id = id;
										js.src = p + '://platform.twitter.com/widgets.js';
										fjs.parentNode.insertBefore(js, fjs);
									}
								}(document, 'script', 'twitter-wjs');
							</script> </span> </span>

				</p>
				<p class="preguntes list-group-item text-justify"  >
					{{ pregunta.toHTML }}
				</p>

			</div>
			{% endfor %}

		</ul>
	</div>

</div>
{% else %}
<p class="col-md-5 col-md-offset-3 text-center">
	En aquest moment no disposem de cap pregunta d'aquest tema.
	<br>
	<strong>Ets professor? Crea'n alguna!</strong>
	<br>
	<br>
	<a href="{% url 'preguntes:crearPregunta' %}">
	<button class="btn btn-info">
		Crear Pregunta!
	</button> </a>
</p>
{% endif %}

{% endblock %}

{% block mesScripts %}
<!--
{% if tipus.nom == "EmplenarBuitsOrtografics" %}
<script src="{% static 'codiEmplenarBuitsOrtografics.js' %}"></script>
{% endif %}
{% if tipus.nom == "CompletarGramatica" %}
<script src="{% static 'codiCompletarGramatica.js' %}"></script>
{% endif %}
{% if tipus.nom == "Test" %}
<script src="{% static 'codiTest.js' %}"></script>
{% endif %}
{% if tipus.nom == "Relacionar" %}
<script src="{% static 'codiRelacionar.js' %}"></script>
{% endif %}-->
{% endblock %}